module SindbadOptimizationExt

import Sindbad: OptimizationBFGS, OptimizationBBOxnes, OptimizationBBOadaptive, OptimizationFminboxGradientDescentFD, OptimizationFminboxGradientDescent, OptimizationGCMAESDef, OptimizationGCMAESFD, OptimizationMultistartOptimization, OptimizationNelderMead, OptimizationQuadDirect

import Sindbad

using Optimization

include("ParameterOptimizationOptimizer.jl")

end
